### ISSUE TITLE
Add CPU affinity to config.

### ISSUE THREAD

**Issue by ehpor** [spacetelescope/catkit2#48]
Allow services to specify an affinity for a specific cores on your CPU. This will help when we want to be a bit more finetuned with where we are putting our computational resources.

**Comment by ehpor** [comment]
Potential entry into `testbed.yml`:

```
cpu_affinity:
  hicatdeuxbis:
    default: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
    boston_dm: [16, 17, 18, 19]
    zernike_control_loop: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  
process_priority:
  default: normal
  boston_dm: high
  zernike_control_loop: high
```
